
import { GoogleOAuthProvider } from "@react-oauth/google";
import "./globals.css";

export const metadata = {
  title: 'Fitz Ai',
  description: 'Generated by Abinanthan',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId={process.env.NEXT_GOOGLE_AUTH_API_CLIENT_ID}>
      <body>{children}</body>
      </GoogleOAuthProvider>
    </html>
  )
}
